### ISSUE TITLE
Dynamic Map Service SetLayers()

### ISSUE THREAD

**Issue by HishamShamas** [Esri/esri-leaflet#1012]
* Browser and version:
Chrome 61

* Version of Leaflet
1.1.0

* Version of esri Leaflet (`L.esri.VERSION`):
2.0.8

Currently, we use the dynamicMapService.setLayers() function to allow users to select/toggle the visible map service layers on the map. The issue we are running into is when the user un-selects all the layers  which sends an empty array of layer ids to the setLayers function resulting, oddly enough, in all the layers appearing. Is this the default intended behavior? how would you recommend handling this scenario. Looking forward to your reply.

**Comment by jgravois** [comment]
thanks for the report. i'd definitely call that a bug.

the problem occurs because we currently only check to see if an array of layers have been supplied manually, we don't make sure that the array actually contains anything.

```js
var empty = L.esri.dynamicMapLayer({
      url:'http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer',
      layers: []
    }).addTo(map);
```
https://github.com/Esri/esri-leaflet/blob/7037f973ab3f16c814260d91109abc1dc82d83c5/src/Layers/DynamicMapLayer.js#L134-L136

it'd be a pretty straightforward change to either make sure the [`export`](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Export_Map/02r3000000v7000000/) request omits _all_ layers or avoid sending off a web request entirely.

is anyone out there interested in taking a stab at writing a patch? i'd be more than happy to help if someone wants to but needs a ✋ .

**Comment by jgravois** [comment]
thank you @Biboba for this fix!
