### ISSUE TITLE
query returnDistinctValues

### ISSUE THREAD

**Issue by joelondon** [Esri/esri-leaflet#1026]
* Browser and version:

ff57

* Version of Leaflet (`L.version`):

1

* Version of esri Leaflet (`L.esri.VERSION`):

2

Steps to investigate:

1. add returnDistinctValues method to query 

2. Implement this feature of the rest service

**Comment by jgravois** [comment]
hello there @joelondon! please see #1001
`distinct` seems like a decent method name to me, but i'm open to other suggestions. 

since setting `returnDistinctValues` requires that `returnGeometry` be set to false, it'd be nice to create the method manually and include the logic there instead of relying on L.esri.Query's generic `setters` object.

**Comment by joelondon** [comment]
hello @jgravois I used the trick from #1001 thanks! You're right, a method that handles geometry will be tidy and `distinct` as a name is good - do you want to do it or shall I?

**Comment by jgravois** [comment]
a pull request would be sincerely appreciated.

**Comment by joelondon** [comment]
stand by (don't hold your breath mind!)

**Comment by joelondon** [comment]
hello @jgravois - I've taken the preliminary step of preparing [a glitch called `frequent-tortellini`](https://glitch.com/edit/#!/frequent-tortellini) - this includes the aforementioned `distinct` method in `src/Tasks/Query.js` 

There's also a test in `spec/Tasks/QuerySpec.js` on `sampleDistinctFeatureCollection` and `sampleDistinctQueryResponse`. The test runs aground though and it seems there's trouble with karma - _maybe I'm being stupid doh_ - ducking around this led back to issue #294: `Fake XHR onreadystatechange handler threw exception: expected null to deeply equal { Object (type, features) }`

Finally, `index.html` runs a couple of sanity check queries on some real data, not so mad it seems.

Would you mind checking on glitch (hope you like pasta).

**Comment by jgravois** [comment]
very cool! the easiest way for me to provide code review would be if you committed your edits in your own branch and opened up a pull request here, even if its a work in progress, so that i can see the diff.

> The test runs aground though and it seems there's trouble with karma

my best guess is that the parameter order produced by the actual API is different from the order your mock service is waiting to respond to.
