### ISSUE TITLE
Sample broken: loading webmaps

### ISSUE THREAD

**Issue by zhif7782** [Esri/esri-leaflet#1040]
The Loading Webmaps sample in http://esri.github.io/esri-leaflet/examples is broken, seems the default webmap (22c504d229f14c789c5b49ebff38b941) does not exist anymore.

![image](https://user-images.githubusercontent.com/7665168/34987205-525279f8-faf5-11e7-9553-d3769b7bc4c5.png)
![image](https://user-images.githubusercontent.com/7665168/34987264-8093dd20-faf5-11e7-8d44-5c4f075347cf.png)

**Comment by jgravois** [comment]
thanks for the heads up!

this can be fixed by substituting [`13750b8b548d48bfa99a9731f2a93ba0`](http://www.arcgis.com/home/webmap/viewer.html?webmap=13750b8b548d48bfa99a9731f2a93ba0) (the other webmap id defined in the sample code). if no one else takes a crack at it first, i'll tackle this when we resolve https://github.com/Esri/esri-leaflet-doc/issues/170

**Comment by jgravois** [comment]
resolved via [`96a6de2`](https://github.com/Esri/esri-leaflet-doc/commit/96a6de26a0efcf2a8672ff16cb67d195b2244319)
