### ISSUE TITLE
Feature Layer can't be added, issue at createNewLayer() with geojson.geometry == null

### ISSUE THREAD

**Issue by ahalota** [Esri/esri-leaflet#1060]
`L.esri.featureLayer({url: 'http://services.arcgisonline.com/arcgis/rest/services/Reference/World_Boundaries_and_Places/MapServer/0'}).addTo(map);`

Runs into issues in FeatureLayer.js at line 37:
```
  createNewLayer: function (geojson) {
    var layer = GeoJSON.geometryToLayer(geojson, this.options);
    layer.defaultOptions = layer.options;
    return layer; },
```
layer is null, i.e. GeoJSON.geometryToLayer failed. 
`geojson.geometry` shows as null.

**Comment by jgravois** [comment]
its deceiving that the footprint layer advertises itself as `esriGeometryPolygon` because the features don't actually have any geometry

https://maps.nccs.nasa.gov/server/rest/services/gliht/201703_PuertoRico_test/MapServer/17/query?where=1=1&f=json

```
"features": [
    {
      "attributes": {
        "Name": "20170301_PRday1b-108-70"
      }
    },
    {
      "attributes": {
        "Name": "20170301_PRday1b-122-30"
      }
    },
    {
      "attributes": {
        "Name": "20170301_PRday1b-92-68"
      }
    }
```
either way, it'd be good for us to trap for edge cases like this within Esri Leaflet instead of forcing developers to hunt down the cause themselves.
