### ISSUE TITLE
set esri.dynamicMapLayer "f" option to "json" and still getting an image

### ISSUE THREAD

**Issue by Djohn12** [Esri/esri-leaflet#1138]
* Browser and version:

Chromium 70.0.3538.77,
Firefox 65.0

* Version of Leaflet :
1.4.0

* Version of esri Leaflet :
2.2.3

Hi,
I'm using esri-leaflet to create a dynamicMapLayer from https://livefeeds.arcgis.com/arcgis/rest/services/LiveFeeds/NOAA_METAR_current_wind_speed_direction/MapServer
I'm adding the layer to my map and it looks great but I wanted to add a class to the features to allow a css hover effect on them.
In the options I have set 'f: "json" but if I look in the console inspector it seems that I'm still getting an image for the layer.
Actually, changing the "f" option doesn't seem to change anything.

Steps to reproduce the error:
1. create a dynamicMapLayer with the option f: 'json'
2. add it to the map
3. open console and look for the layer in <div class="leaflet-pane leaflet-overlay-pane">
4. you'll see an element <img class="leaflet-image-layer"> with a src attribute equal to the url set in the layer options

With the parameter set as "json" I expected each features to be a layer and not to have an image element overlaying the map

I'm not sure if I missed anything and didn't really understand how to use dynamic layers or if this is some kind of bug...

Also, I tried to use the getLayers() method I saw on the documentation but it keeps returning false.
After some research I tried to use the process you described in [#566](https://github.com/Esri/esri-leaflet/issues/566) but using L.esri.request on my url keeps getting me an error code : 499, message : "Token Required" and the response always returns null

Your project is really terrific, I hope I'm not disturbing you only because I'm using it wrong...

Best Regards

Edmond

**Comment by jgravois** [comment]
the reason setting `f: "json"` doesn't do anything for dynamicMapLayer is because thats already the default.

this doesn't mean you get JSON features back, it means you get a JSON response which includes the url of the output image.

if you haven't already seen it, the tutorial below does a good job of comparing and contrasting the different layer types.

http://esri.github.io/esri-leaflet/tutorials/introduction-to-layer-types.html

> using L.esri.request on my url keeps getting me an error code : 499, message : "Token Required"

that's because you're pointing at a premium service that only support authenticated requests.

http://esri.github.io/esri-leaflet/examples/premium-content.html

**Comment by Djohn12** [comment]
I don't understand, I don't see any difference in the response when changing the param to 'image' and my layer will still look the same on the map or when logging it.

But if I get it right, the solution for me would probably be to use the FeatureLayer version of the ressource as I'd like to manipulate the features a little.

About the error, I understand the service is a premium one so I'll need to authenticate to use it in my application but how come I am still able to get and add the dynamic layer to my map without login ? I can even access the resource metadatas.
I'm only getting the error when making use of certain methods.
Also, my layer didn't show on chromium at first and I was getting that error then suddenly it worked without me changing any of my code.

Would that be a flaw in the authentication checking from the arcgis service ? Or maybe part of the service is free to access ?

**Comment by jgravois** [comment]
the difference is pretty subtle.

choosing `f: "image"` asks ArcGIS Server to return the actual image in the `/export` response (instead of returning JSON that includes the URL of the output image).

In the client application ultimately the image is going to be drawn either way.

as for your other question, it certainly _sounds_ like something is misconfigured. I'd expect the whole thing to either be public or require a login.

**Comment by Djohn12** [comment]
Thank you for those details, it does put a new light on the trouble I was having.
I think I'll try to contact argis about the stuff I manage to get without proper authentication.

Also, I'll now make sure to check the availability of the content I want to use and pass it an arcgis token if needed -_-'

Sorry to disturb again, hope this can help someone in the future :)
Thanks for everything
