### ISSUE TITLE
Attribution is now a json url instead of jsonp

### ISSUE THREAD

**Issue by jubasse** [Esri/esri-leaflet#1142]
* Browser and version:

Chrome 51

* Version of Leaflet (`L.version`):

^1.3.3

* Version of esri Leaflet (`L.esri.VERSION`):

^2.2.3 updated today to the last version

Steps to reproduce the error:

instanciate the map with a `featureLayer`.
Until today i do not have any problem, but today, it seems like the attribution url doesn't send the same data anymore, because in the library script, we have the `_getAttributionData` that send a `jsonp` request to arcgis, but now the given url [https://static.arcgis.com/attribution/World_Topo_Map?callback=window._EsriLeafletCallbacks.c0&f=pjson](https://static.arcgis.com/attribution/World_Topo_Map?callback=window._EsriLeafletCallbacks.c0&f=pjson) returns a json, and this json isn't recognize (header text/plain).

I think that we should now use an http request to get data instead of jsonp..

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using: npm

**Comment by jgravois** [comment]
thanks for the report.

my hunch is that this was a bug introduced during [yesterday's ArcGIS Online release](https://www.esri.com/arcgis-blog/products/arcgis-online/announcements/whats-new-in-arcgis-online-march-2019/), but i'll need to confirm.

**Comment by jgravois** [comment]
it turns out we made a conscious choice to turn off JSONP support on static.arcgis.com to retire some old infrastructure and optimize our CDN.

in Esri Leaflet land we _should_ have been using `L.esri.request()` all along, but i can't go back in time. folks are going to have to upgrade to [v2.2.4](https://github.com/Esri/esri-leaflet/releases/tag/v2.2.4) to ensure their app continues to display attribution dynamically.

thanks for opening this issue to bring it to my attention!

**Comment by zbeat** [comment]
@jgravois Thx for the quick fix, as well as this additional info on the AGOL change:
> it turns out we made a conscious choice to turn off JSONP support on static.arcgis.com to retire some old infrastructure and optimize our CDN.

**Comment by jubasse** [comment]
@jgravois Thanks for the quick fix !
