### ISSUE TITLE
setTimeRange on a FeatureLayer doesn't works. 

### ISSUE THREAD

**Issue by geocot** [Esri/esri-leaflet#1148]
* Browser and version: Chrome 73.0.3683.86 and Firefox 66.0.2 (64 bits)

* Version of Leaflet (`L.version`):

Latest 

* Version of esri Leaflet (`L.esri.VERSION`):

 `master`

Steps to reproduce the error:

I'm using the from and to in the featurelayer option and everything work fine. But I'm trying to use the method setTimeRange with the same date that I used for the options and it doesn't work. I got thise error " FeatureManager.js:365 Uncaught TypeError: Cannot read property 'between' of undefined"

I was expecting: To filter my data by using the time range. 

![Annotation 2019-04-03 201604](https://user-images.githubusercontent.com/7696799/55521125-5f215000-564d-11e9-9b73-38b3133b456b.jpg)

**Comment by geocot** [comment]
Hi again, I found the "problem". I need to use the "timeField" option when i'm using the method setTimeRange. But when the from and to are used as an options, you don't need to use "timeField" option. If this can help someone.

**Comment by jgravois** [comment]
nice debugging!

this happens because calling `setTimeRange()` requires that we invoke logic internally to filter features that have already been queried from the service and displayed previously to ensure that they are within the new time range.

when you set the constructor option, we only ever fetch features that match the time filter, so we don't need to know the name of the field that stores the information.

all that said, if anyone is keen to make this easier on the next guy or gal in @geocot's shoes, they could insert a console.warn in the block below to let them know that its only possible to manipulate a time filter if a `timeField` is provided in the constructor.

https://github.com/Esri/esri-leaflet/blob/bcd44fb5074d0bc7b9435fc47cc31198c2589e65/src/Layers/FeatureLayer/FeatureManager.js#L53-L55

**Comment by patrickarlt** [comment]
Since @gavinr added a warning I'm closing this.

**Comment by gavinr** [comment]
Thanks for the cleanup @patrickarlt!
