### ISSUE TITLE
"Powered by Esri" Map Attribution doesn't go away when you run Map.removeLayer(...) on an esri-leaflet map

### ISSUE THREAD

**Issue by timothycouchhsi** [Esri/esri-leaflet#1239]
## Describe the bug

If you add and then later remove an esri-leaflet layer, the "Powered by Esri" attribution stays on the map.

## Expected behavior

I'm trying to make a toggleable esri-leaflet layer. I would like to have Powered by Esri come up when I toggle one of these layers on, then I would like it to remove from the attributions when I toggle the layer back off. 

## Actual behavior

I'm using L.Map.removeLayer to remove my esri-leaflet map layer, but the "Powered by Esri" attribution stays on the attribution even when the layer is gone. It does not create multiple attributions if I toggle the layer many times or have multiple esri-leaflet layers at once.

## Screenshots

![image](https://user-images.githubusercontent.com/29982559/98412891-591bfe00-203e-11eb-83c1-fb44d265a633.png)

## Environment Information

- Version of Leaflet - 1.3.1
- Version of Esri Leaflet 2.3.3, 2.5.1
- Your OS: Windows 10
- Browser and Version Chrome 86.0.4240.183 64-bit

## Additional context

Using webpack.

Thank you!

**Comment by gavinr** [comment]
Hi, thanks for posting this issue. What kind of layer are you seeing this behavior with (Basemap Layer, Feature Layer, etc)? 

Do you have a jsbin that demonstrates the issue?

Thanks!

**Comment by timothycouchhsi** [comment]
I'm using a dynamicMapLayer and a tiledMapLayer for base layers. Sorry, but I don't have a jsbin to show. Thank you for checking this out!

**Comment by jwasilgeo** [comment]
Thanks for the additional info but a live public demo would be extremely useful and helpful. If not JSBin, perhaps you could us <https://codesandbox.io> or <https://codepen.io/pen/> or provide a full html/js/css code sample re-using some public layer resources available at the demo pages <https://esri.github.io/esri-leaflet/examples/>?

**Comment by pjbiogit** [comment]
I have also run into this problem. You can see a simple demonstration [here](https://codepen.io/pjbiogit/pen/RwGLaaN). After adding the layer (via button) the attribution is added to the map, but then when removing the layer (pressing the other layer) the attribution is not removed. 

This example uses a feature layer rather than a dynamic map layer or tiled map layer, although it looks like the logic for `FeatureManager.js`, `BasemapLayer.js`, `TiledMapLayer.js`, and `RasterLayer.js` all call `setEsriAttribution(map)` in the `onAdd` function, but never remove the attribution in an `onRemove` function, so I would expect similar performance for any of them.

Since the `setEsrAttribution(map)` function is setting the attribution prefix, I believe it does not get removed properly when the layer gets removed like other layer attributions.

**Comment by gavinr** [comment]
Thanks for the additional info @pjbiogit. Just like the `L.esri.featureLayer`, `L.esri.basemapLayer` is supposed to set the Esri  attribution string, so I've simplified your example a bit to not use `L.esri.basemapLayer` so that we can focus on `L.esri.featureLayer` in this issue:
https://codepen.io/gavinr/pen/XWjVRVZ?editors=1000

For `L.esri.featureLayer`, the Esri attribution is getting added here:
https://github.com/Esri/esri-leaflet/blob/f572dbad34d6aef5b94eface5c0b73da5bbd9caa/src/Layers/FeatureLayer/FeatureManager.js#L71 (within the `onAdd` function), and based on this GitHub issue, it should be removed here:
https://github.com/Esri/esri-leaflet/blob/f572dbad34d6aef5b94eface5c0b73da5bbd9caa/src/Layers/FeatureLayer/FeatureManager.js#L113-L117 - but it's not, and that's the problem.

When this code was last touched: https://github.com/Esri/esri-leaflet/pull/841/files ... it seems like the code to remove the attribution on layer remove was simply missed (others please chime in if I'm missing something here). Given all that, a PR would be welcomed to remove the attribute in the `onRemove` function of `src/Layers/FeatureLayer/FeatureManager.js`. I assume this is probably a problem in the other layer types too, so probably makes sense to fix them all at the same time.

**Comment by gavinr** [comment]
Fixed in https://github.com/Esri/esri-leaflet/releases/tag/v2.5.2
