### ISSUE TITLE
Examples in Documentation return 401 error

### ISSUE THREAD

**Issue by dennisdebel** [Esri/esri-leaflet#1387]
### Description

Following the instructions on https://developers.arcgis.com/esri-leaflet/maps/display-a-map/ with my own correct API key results in 401 error and not map being displayed. Both on CodePen, locally and on my own https server.

### Link to page

https://developers.arcgis.com/esri-leaflet/maps/display-a-map/

### Link to CodePen

https://codepen.io/dennisdebel/pen/abxorxJ (obviously redacted API key)

**Comment by gavinr-maps** [comment]
Hi, can you please post a link to the codepen?

**Comment by dennisdebel** [comment]
Added to the original post!

**Comment by gavinr-maps** [comment]
Hi, when I put an API key into your codepen, it works ok for me:

![image](https://github.com/Esri/esri-leaflet/assets/137905994/02a17602-3500-488c-907a-15822bd44086)

So I would guess that maybe you need to use a correct API key.

I'm going to close this issue since it's not an issue with the Esri Leaflet code. If you continue to have challenges with using Esri Leaflet, please post in the [Esri Community](https://community.esri.com/t5/open-source-mapping-libraries-ques/bd-p/open-source-mapping-libraries-questions) or reach out to Esri Tech Support. Thanks!

**Comment by dennisdebel** [comment]
Dear @gavinr-maps, I see the confusion now, I used the default API key that is present when you create an account. When I generated a new one, the exampled worked! Maybe it is an idea not to give a new user a default non working API key (what is the rationale behind this? as example?), but instead force a new user to generate a new key.
