### ISSUE TITLE
Breakout website into its own repo

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#370]
The Esri Leaflet website shouldn't really be tied to this repo. This means that issues with plugin docs have to end up here which seems a little confusing.

Moving the website also gives us the opportunity to update the design and incorperate docs for plugins.

**Comment by jgravois** [comment]
not sure if you were planning on incorporating a redesign at the same time, but i broke out the website into its own repo [here](https://github.com/jgravois/esri-leaflet-website)

**Comment by jgravois** [comment]
reminder of goal to include doc for plugins alongside the rest of the api.

**Comment by jgravois** [comment]
now that we finally have the plugin doc in the esri leaflet website, i refreshed my previous work of breaking it out into its own seperate repo.  if you still want to do this, i'll ask the admins to move it into the [esri](http://github.com/Esri) organization after everyone's happy.

https://github.com/jgravois/esri-leaflet-doc
http://jgravois.github.io/esri-leaflet-doc/

should be dead simple.  the only two pending issues i can think of are:
1. creating an advanced configuration which loads `dist/esri-leaflet.js` from an entirely seperate directory (so that devs can test the samples against a custom build)
2. making sure the new site/url, redirects back (or vice versa)
