### ISSUE TITLE
Difficulty understanding Dynamic Map Layer, MapServer, FeatureServer

### ISSUE THREAD

**Issue by buckleytom** [Esri/esri-leaflet#403]
Hello, 

I was trying to follow this example: 

http://esri.github.io/esri-leaflet/examples/spatial-queries.html

With the following MapServer layer:

http://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Environment/MapServer/23/

I became confused about whether I should use the DynamicMapLayer or FeatureServer classes from leaflet-js, partially because of the inconsistencies in their naming. That is, an ArcGIS Rest endpoint uses the endpoint /FeatureServer, and so does leaflet-js. However, leaflet-js does not seem to have a L.esri.mapServer class. 

This meant that I just went back to using Terraformer. In any case, these tools are pretty great overall.

**Comment by NickKyriakidis** [comment]
Hello! 

MapServer is a collection of layers usually, so I would like to know if there is a way to load all the layers at once. I use dynamicMapLayer and still that doesn't work. I also tried with the mapServer that @buckleytom provided, same results!

**Comment by jgravois** [comment]
just to clarify/reiterate, the `dynamicMapLayer` constructor expects a url that ends in '/[yourservice]/MapServer/` and asks the server to draw a raster image on the fly, displaying multiple layers at once.  (check out the example [here](http://esri.github.io/esri-leaflet/examples/dynamic-map-layer-reprojected.html)).

the `featureLayer` constructor expects a url that ends in a number (like 'MapServer/3' or 'FeatureServer/0') and asks the server for JSON so that a graphic can be drawn on the client.

confusingly, the dynamic map service url @buckleytom provided in the first comment in this thread was published with all the individual layers 'not visible' by default.  you can open this [arcgis.com webmap](http://www.arcgis.com/home/webmap/viewer.html?url=http%3A%2F%2Fmaps2.dcgis.dc.gov%2Fdcgis%2Frest%2Fservices%2FDCGIS_DATA%2FEnvironment%2FMapServer%2F), click the `content` tab and expand the `environment` layer to see what i mean.

this doesn't mean its not possible to draw the layers, but you'd have to provide an array of `layers` in the [constructor](http://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html) to override the default behavior.
