### ISSUE TITLE
should we document object 'properties' in API reference?

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#461]
our API reference is consistent with Leaflet's, but both Google Maps and the JSAPI provide information about object properties in addition to methods and events.

do we consider them private by default?
if not, is there some other specific reason that they are ommited?

for me anyway, as a hack programmer, it makes an API a lot more mysterious when i can't traverse objects available as properties on other objects.

**Comment by patrickarlt** [comment]
Since nothing is private in JavaScript I've just used the `_` convention. Anything that starts with `_` is 'private' and is subject to change in any release at any time without notice.

That said most things don't have a lot of properties just `options` and `url`. Which really shouldn't be changed anyway. Leaflet gets away with this by offering methods `getWhatever` and `setWhatever` when you might need to get or set a property which is probably safer in the long run.

Are there any additional things you think we need to be able to access that aren't possible through methods?

**Comment by jgravois** [comment]
i can't say there was a particular property which spurned this issue, i just noticed the high level discrepancy in documentation.

given the convention in Leaflet that more often than not properties are inherited in a constructor and cannot be modified later, i think we're okay with what we have, but i'll keep an eye out for interesting public properties in individual classes in the future to make sure they're exposed somehow...
