### ISSUE TITLE
Request callback called twice when XHR gets a CORS error

### ISSUE THREAD

**Issue by timbonicus** [Esri/esri-leaflet#465]
I'm using Layer.identify against a server that triggers a cross-origin resource sharing (CORS) error:
```
XMLHttpRequest cannot load https://apps.fs.fed.us/ArcX/rest/services/EDW/EDW_ForestSystemBoundaries_01…04.52667236328125%2C40.7701418259051&geometryType=esriGeometryPoint&f=json. The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:8080, *', but only one is allowed. Origin 'http://localhost:8080' is therefore not allowed access.
```

In this scenario, Request.js calls the callback twice - first from the onreadystatechange block, then again from the httpRequest.onerror.

Should the onreadystatechange block skip processing for certain error codes? I'm not sure if this is an issue with Request.js or something strange about how the request is being handled.

**Comment by jgravois** [comment]
> Request.js calls the callback twice
can you explain this in a little more depth?

is everything good when you set the appropriate `{useCors: false}` flag for the layer?

**Comment by timbonicus** [comment]
Yes, setting useCors:false on the layer makes the XHR error go away. It seems like useCors:true would be the preferred setting to work with more services; I'm surprised that a JSONP request would fail where a JSON request succeeeds. Is there something I'm not getting?

Regardless, I'm curious about the code problem. It appears that a failed XHR due to CORS fires both onreadystatechange and onerror, which is also surprising. Should Request.js check for status == 200 on the onreadystatechange?

**Comment by patrickarlt** [comment]
If you Google "[The 'Access-Control-Allow-Origin' header contains multiple values](https://www.google.com/search?q=The+%27Access-Control-Allow-Origin%27+header+contains+multiple+values&oq=The+%27Access-Control-Allow-Origin%27+header+contains+multiple+values&aqs=chrome..69i57j0l5.346j0j7&sourceid=chrome&es_sm=91&ie=UTF-8)" you can see a lot of StackOverflow questions about misconfigured servers. All of the server examples on http://enable-cors.org/server.html only set 1 origin even though the spec allows for multiple.

CORS errors are hard to trap for a reason see http://stackoverflow.com/questions/4844643/is-it-possible-to-trap-cors-errors. But I can mess around with this a little and see if I can make the callback run only once. However you probably need to tweak your server configuration to fix this error going forward.

If you need to test your server config a good way is to also copy/paste the URL into ArcGIS Online and look at your console. The metadata request will fail but the images will render because image loading can be cross domain.

![my_map_and_index_html_ _esri-leaflet_and_main_js_ _developers-site](https://cloud.githubusercontent.com/assets/378557/6426867/f47382a2-bf22-11e4-902b-80cc27e23d5b.png)

**Comment by timbonicus** [comment]
Thanks, Patrick! That's good information. Unfortunately, this isn't my server - users can add their own custom layers, so this was just an example of a third-party server causing trouble. This fix will help on the error-handling side.
