### ISSUE TITLE
Requests are failing with unsupported format error.

### ISSUE THREAD

**Issue by jbritton** [Esri/esri-leaflet#486]
While trying to query a map service, I'm receiving invalid format errors.  It appears that the Query class is changing the 'f' parameter to geojson on line 97 of Query.js.  Issuing the GET request with f=json works as expected.  Is there any good way around this?  Here's my code:

            var token = '<INSERT_TOKEN>';
            var url = 'http://demographics4.arcgis.com/arcgis/rest/services/USA_Demographics_and_Boundaries_2014/MapServer/9';

            var map = L.map('map',{}).setView([38.0, -96.0], 5);
            L.esri.basemapLayer('Gray').addTo(map);
            L.esri.basemapLayer('GrayLabels').addTo(map);

            var mapService = L.esri.Services.mapService({
                url: url,
                token: token,
                useCors: true
            });

            mapService.authenticate(token);

            map.on('click', function(e){
  
                mapService.query()
                        .contains(e.latlng)
                        .fields(['ID','NAME','TSEGNUM','OBJECTID'])
                        .run(function(){
                            console.log(arguments);
                        });

          });

**Comment by jgravois** [comment]
at present Esri Leaflet is incorrectly assuming that all services hosted on the `arcgis.com` domain support `geojson` output.

the code change below implemented [here](https://github.com/Esri/esri-leaflet/blob/master/src/Util.js#L402) should correct the problem.
```
EsriLeaflet.Util.isArcgisOnline = function(url){
    //the regex needs to look something like this
    return (/\.arcgis\.com/g/FeatureServer/g).test(url);
  };
```

if you're not interested in recompiling the source and hosting it alongside your own application, you might also consider rolling back to [Release Candidate 4](https://github.com/Esri/esri-leaflet/releases) before the new `feature` was included (as long as you aren't affected by any other bugs we've fixed since then.

hope that helps.  thanks for catching the problem and articulating the error so clearly.

**Comment by jbritton** [comment]
Great, thanks.  I can patch it locally for my own purposes.  Nice work on esri-leaflet, by the way.

**Comment by patrickarlt** [comment]
@jgravois could you turn this into a PR?

**Comment by jgravois** [comment]
absolutely.  was just waiting until I had a chance to update tests at the same time.
