### ISSUE TITLE
esri-leaflet basemap list does not match ESRI javascript api basemap list

### ISSUE THREAD

**Issue by marsmith** [Esri/esri-leaflet#504]
The naming conventions are different, and the list of basemaps is different:

esri-leafet basemap list (from [API docs](http://esri.github.io/esri-leaflet/api-reference/layers/basemap-layer.html)):

- Streets 
- NationalGeographic 
- Oceans 
- Gray 
- DarkGray 
- Imagery
- ShadedRelief

ESRI javascript API basemap list (from [API docs](https://developers.arcgis.com/javascript/jsapi/basemaptoggle-amd.html))

- streets
- satellite
- hybrid
- topo
- gray
- dark-gray
- oceans
- national-geographic
- terrain
- osm

So, "hybrid", "osm", and "topographic" do not exist for esri-leaflet, and naming conventions are different for "satellite" ("imagery") and "terrain" ("ShadedRelief").

It would be really helpful if these were consistent, and all options were available.

**Comment by jgravois** [comment]
@patrickarlt may want to chime in too, but i don't think we have any plans to ensure consistency between the basemap options in the JSAPI and those in Esri Leaflet, because the behavior was intentionally designed slightly differently in this API.

1. in Esri Leaflet, we intentionally segregate basemaps from their labels (for example, developers can add only the 'Gray' basemap, or add both 'Gray' and 'GrayLabels')
2. the OpenStreetMap basemap option in the JSAPI loads a non-esri tiled map service.  this isn't something we want to broker in Esri Leaflet either, as its something that can be accomplished directly via core Leaflet (see an example [here](http://esri.github.io/esri-leaflet/examples/geocoding-control.html)).

**Comment by BlakeDraper** [comment]
I respect that the behavior is different between the two APIs, and that there is no plan to bring the basemap options into consistency with each other,  but I fail to see why the strings used to specify the basemaps can't be consistent where direct counterparts exist.

Example: "streets" in the JSAPI and "Streets" in esri-leaflet; "national-geographic" in JSAPI and "NationalGeographic" in esri-leaflet. Would be great if those strings were consistent.

**Comment by marsmith** [comment]
@jgravois 

I understand your points 1 and 2 regarding the labels and the OSM map.  There are still blatant discrepancies however.  For example between "Terrain" and "ShadedRelief", and the esri-developed basemap "topo"  and "hybrid" not existing in esri-leaflet.  Also, one uses older camel-case notation vs newer lowercase slug-notation. 

I can submit a pull request with these changes?

**Comment by jgravois** [comment]
> 3. Topographic is already a basemap keyword in the doc you linked above. Hybrid can be achieved by adding both 'Imagery' and 'ImageryLabels'

I made an additional edit to my initial response regarding 'topo' and 'hybrid' basemaps.

I don't know if i'd agree that CamelCase is somewhow older than lowercase notation.  In general I think our interest and intention in developing Esri Leaflet was to adhere to existing Leaflet conventions as much as possible.  

I wouldn't say i'm adamant about it, but my gut reaction is that its not worth introducing a breaking change to try and ensure semi-consistency.  If @patrickarlt and the other maintainers disagree, then a Pull Request would be helpful.

**Comment by marsmith** [comment]
@jgravois 

You are right, not sure why I missed "Topographic" when copying and pasting that list from esri-leaflet [edited original post].  The remaining discrepancy is "ShadedRelief" and "terrain", and the casing and abbreviation differences.  

My initial thoughts were that if you have a basemap constructor in the two API' that behaves in pretty much identical ways, the constructor should use the same options for referencing the same basemaps.  I understand not wanting to break things for existing esri-leaflet users, however. Thanks for your concern here, let me know about the pull request.

**Comment by jgravois** [comment]
trust me.  i *totally* understand the perspective that all idiosyncratic differences between various ArcGIS products should be eradicated on sight.  lets see what the other folks have to say.

**Comment by patrickarlt** [comment]
There a couple of reasons for the discrepancies.

1. Like @jgravois mentioned earlier, Esri Leaflet separates labels from base layer, this is mostly so you have more control and we don't have to do anything complicated under the hood. Each layer is simply an L.TileLayer, rather then a LayerGroup with base+tiles that has to be managed.
2. Separating labels from basemaps also allow you to mix and match. For example in the JS API `hybrid` is satellite + boundary labels, but in Esri Leaflet I can use satellite + transportation, or dark canvas + satellite boundary labels (a personal favorite) without having to lookup service urls.
3. I opted for uppercasing things like `'NationalGeographic'` because I saw them as constants (which they are) which in other languages (Ruby) are upper cased. I think this is clearer then lower casing them. This also lines up with Leaflet because they are declared as static variables on the class.
4. I expanded  `topo` to `Topographic` make it clearer.

I'm against changing this for a few reasons.

1. While we can map the single layer basemap keys like `topo`, `national-geographic`, `satellite` and `streets` all the other keys in the JS API are composites of 2 or more layers which would mean breaking API changes.
2. In 4.0 the JS API will introduce a Basemap class https://ycabon.github.io/ds2015-arcgis-api-for-javascript-the-road-ahead/#/12 that handles some interesting concerns.

`Terrain` is actually a key just not documented (We need to fix that) https://github.com/Esri/esri-leaflet/blob/master/src/Layers/BasemapLayer.js#L165-L187.

**Comment by jgravois** [comment]
thanks for clarifying @patrickarlt.  previously i was under the mistaken impression that 'terrain' in the JSAPI mapped to 'ShadedRelief' in Esri Leaflet.

i'll submit a PR shortly to get the additional layer into the documentation.

**Comment by patrickarlt** [comment]
For whatever reason we have both a [Terrain](http://www.arcgis.com/home/webmap/viewer.html?webmap=aab054ab883c4a4094c72e949566ad40) AND a [Shaded Relief](http://www.arcgis.com/home/webmap/viewer.html?webmap=3c93bbf238424a3e85aae19823fc92ea)

**Comment by BlakeDraper** [comment]
Thanks @jgravois and @patrickarlt for the careful consideration and explanation. 4.0 JSAPI does look like a great step forward, too.

**Comment by patrickarlt** [comment]
@marsmith @BlakeDraper At some point this year (probably after JS API 4.0) there will be a vector basemap plugin for Esri Leaflet which would be a good opportunity to consider this again.

**Comment by marsmith** [comment]
Thanks for the feedback and clarification.   Weird, it looks like Terrain and Shaded relief are the same data, with some color differences.
