### ISSUE TITLE
Don't replace double-quotes in where string

### ISSUE THREAD

**Issue by blkqi** [Esri/esri-leaflet#521]
Currently EsriLeaflet.Tasks.Query will replace any and all double quotes (") in a where string with quoted single-quotes (\'). Double quotes are perfectly valid in SQL and some backends require them in order to properly specify certain identifiers.

**Comment by patrickarlt** [comment]
I have long wondered if this would cause issues. The original reason this happens is that ArcGIS Online does not accept double quotes. Anyone attempting to do something like `layer.setWhere('BIKEMODE="Low traffic through street"')` would actually produce an error. Since the error message is totally unhelpful I decided to replace double quotes with single quotes to make it work.

**Double  quotes** (error) [http://services.arcgis.com/uCXeTVveQzP4IIcx/ArcGIS/rest/services/Bike_Routes/FeatureServer/0/query?where=BIKEMODE="Low traffic through street"](http://services.arcgis.com/uCXeTVveQzP4IIcx/ArcGIS/rest/services/Bike_Routes/FeatureServer/0/query?where=BIKEMODE="Low traffic through street")

**Single  quotes** (no error) [http://services.arcgis.com/uCXeTVveQzP4IIcx/ArcGIS/rest/services/Bike_Routes/FeatureServer/0/query?where=BIKEMODE='Low traffic through street'](http://services.arcgis.com/uCXeTVveQzP4IIcx/ArcGIS/rest/services/Bike_Routes/FeatureServer/0/query?where=BIKEMODE='Low traffic through street')

I'm to see if this is something that can be resolved in the backend of ArcGIS Online and then we can eliminate this.

**Comment by patrickarlt** [comment]
@blkqi do you have example of a public facing service that I can use as an example besides something hosted/in Online?

**Comment by patrickarlt** [comment]
By that I mean something where you absolutely MUST use doublequotes.

**Comment by blkqi** [comment]
@patrickarlt the first form of your where clause produces an error because it is syntactically invalid. The second form is correct and so is the following form which utilizes double-quotes [1]: 
```
"BIKEMODE"='Low traffic through street'
```
See: 
- [http://services.arcgis.com/uCXeTVveQzP4IIcx/ArcGIS/rest/services/Bike_Routes/FeatureServer/0/query?where="BIKEMODE"='Low traffic through street'](http://services.arcgis.com/uCXeTVveQzP4IIcx/ArcGIS/rest/services/Bike_Routes/FeatureServer/0/query?where=%22BIKEMODE%22%3D%27Low%20traffic%20through%20street%27)
- http://resources.arcgis.com/en/help/main/10.2/index.html#/SQL_reference_for_query_expressions_used_in_ArcGIS/00s500000033000000/

Sorry, I don't have a public example of where double-quotes are strictly required. This is generally enforced by the specific backend data store being used.

**Comment by jgravois** [comment]
thanks for taking the time to explain that @blkqi.  that's new info for me.

this might be too much of a hack, but if @patrickarlt wants to try and keep the existing logic to minimize unintended syntax errors, perhaps we can just check to make sure the provided string doesn't include both single and double quotes before converting and escaping?

```
where: function(string){
    // check to make sure where clause isn't denoting fieldnames with doublequotes
    if !(string.includes('"') & string.includes("'")){    
      this.params.where = string.replace(/"/g, "\'"); // jshint ignore:line
    }
    return this;
  },
```
we could also just stop manipulating the string provided by the developer entirely..

**Comment by blkqi** [comment]
IMO it would be much preferable to let the backend do the syntax checking on the (untouched) where string, and have the necessary error handling in place to propagate syntax and other errors to the client. Of course I realize that this is a breaking change that may not feasible to implement right away.

For my purposes, a simple method to get double-quotes passed to the backend at all would be sufficient. Just let me know if I can help out.

**Comment by patrickarlt** [comment]
> IMO it would be much preferable to let the backend do the syntax checking on the (untouched) where string

I totally agree with you here but I also think the backend should be able to correct a simple mistake like putting a string value in double quotes if you don't know any better.

Reading through http://stackoverflow.com/questions/1992314/what-is-the-difference-between-single-and-double-quotes-in-sql and http://stackoverflow.com/questions/214309/do-different-databases-use-different-name-quote/214344#214344 It looks like most databases use double quotes for table/column names which might be non-standard like those that contain whitespace.

White space seems to be the main reason to use double quotes. But that said I cant find a single service in ArcGIS Online or on any one of our sample servers that uses whitespace in a field name.

If you need to access a field name with whitespace this post suggests that you can use `[column name]` in MS SQL Server http://stackoverflow.com/questions/214309/do-different-databases-use-different-name-quote/214344#214344 

Since AGOL is on MS SQL Server (I think) this works just fine http://services.arcgis.com/uCXeTVveQzP4IIcx/ArcGIS/rest/services/Bike_Routes/FeatureServer/0/query?where=[BIKEMODE]%3D%27Low%20traffic%20through%20street%27.

**Comment by blkqi** [comment]
> I totally agree with you here but I also think the backend should be able to correct a simple mistake like putting a string value in double quotes if you don't know any better.

Your call if you want to do that, but in any case we should not be munging valid syntax into invalid syntax.

One example of when you would _need_ double-quotes is when using a PostgreSQL backend and trying to reference a delimited identifier; for example, id vs. "ID". This will be equally true for any data store which supports ANSI SQL (e.g. [SQL-92]).

[SQL-92]: http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt

**Comment by blkqi** [comment]
Sorry for temporarily closing the issue guys -- I simply hit the wrong button :-)

**Comment by jgravois** [comment]
> I simply hit the wrong button :-)
no worries.  it happens **all** the time.

i agree with you here @blkqi .  im in the middle of a PR which will:
1. add example syntax to deter newbs like me from using doublequotes to encase actual string values
2. remove our current string manipulation
3. introduce error trapping for generic `400 - Unable to complete messages` and take the opportunity to inject a more helpful message.

**Comment by patrickarlt** [comment]
@blkqi In case you didn't catch it @jgravois is working on this in #524.

**Comment by blkqi** [comment]
Thanks for the update @patrickarlt , and thanks for looking into this @jgravois !

**Comment by patrickarlt** [comment]
@blkqi If you are in massive need of this now you can follow the development instructions https://github.com/Esri/esri-leaflet#development-instructions and run `grunt build` locally to get distribution ready files. Otherwise this will land in the next release.

**Comment by jgravois** [comment]
closing (as #524 has been merged).
