### ISSUE TITLE
Performance issue of Services.featureLayer in Internet Explorer

### ISSUE THREAD

**Issue by jiantongc** [Esri/esri-leaflet#572]
I know there's a closed issue #212 similar to this, but this actually just affects older browsers (IE8, IE9, etc.)

Please take a look at http://jsfiddle.net/jiantongc/9j5wyj7h/, IE8 will show the notorious "Stop running this script?" prompt
(even jsFiddle doesn't support IE8, so I'm pasting the code snippets here:)
```
L.esri.Services.featureLayer({
        "url": URL
    })
            .query()
            .where(WHERE_CLAUSE)
            .run(function (error, featureCollection, response) {
                   // browser froze before the callback, see attached image
             }
```
Is the 'run' statement -> 'run' statement executes the request to ArcGis Server to get the requested geo data, then transforms the received data into {{featureCollection}} where it can be drawn. 
I didn't really dig deep into the code, but I think internally, is 
``` L.esri.Util.arcgisToGeojson(features[i], fid); ``` that causes the problem. The algorithm could be somehow optimized, or we just need to handle it for older javascript engine (by using timeout loops, oslt).

I think the feature layer is pretty small (at least not large), is only about ~100kb. 
PS: Esri-Leaflet can handle thousands of *really* small features, but not a single *relatively large* feature.

(https://cloud.githubusercontent.com/assets/1732625/8518211/54cdfd9c-240b-11e5-8f45-c7a5125d82f4.png)

**Comment by patrickarlt** [comment]
In order to get the maximum accuracy for the conversion you have to do A LOT of checks and loops. It is also seriously difficult to optimize for older JavaScript engines like IE 8 and 9. Your best bet is to take advantage of server side simplification via the `simplify` method even a small amount of simplification (im using 0.0125) can make a big difference http://jsfiddle.net/9j5wyj7h/2/ runs about twice as fast in Chrome. You could also conditionally apply this based on something like `L.Browser.ielt9`.

**Comment by jgravois** [comment]
closing, but happy to chat more if @jiantongc has any more questions/concerns.
