### ISSUE TITLE
metadata requests with an invalid token don't trigger the callback

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#575]
```js
L.esri.Services.service({
  url: 'http://logistics.arcgis.com/arcgis/rest/services/World/ServiceAreas/GPServer/GenerateServiceAreas',
  token: 'badtoken'
}).metadata(function(error, response){
  // never triggered
  console.log(error);
});
```
this is because we currently:
 1. trap authentication errors
 2. push into `_requestQueue`
 3. intentionally don't call the callback.

(code [here](https://github.com/Esri/esri-leaflet/blob/master/src/Services/Service.js#L73-L80))

i don't know enough about the other use case we are trying to support to know if/how we can best 'fix' this problem.  i was just surprised to see the error swallowed while working on jgravois/esri-leaflet-gp/issues/17

**Comment by jgravois** [comment]
substituting this would work (and i believe not screw up the current intention of trapping requests with no token at all).
```js
if (error && (error.code === 499 || error.code === 498 && !params.token)) {
```

**Comment by patrickarlt** [comment]
This is actually how I intended it to work to avoid callbacks being called twice. Generally the expectation is that callbacks will only be called once. If we wanted to move to calling callbacks multiple times everyone would have to write their callbacks in such a way that they never ran code on errors. This means that all callbacks would have to be written like this:

```js
function(error, response, raw){
  if(error) {
    //handle error
  } else { 
   // handle success
  }
}
```

or

```js
function(error, response, raw){
  if(error) {
    //handle error
    return;
  }

  // handle success
}
```

because this means that if you write callbacks like this:

```
function(error, response, raw){
  if(error) {
    //handle error
  }

  // handle success
}

you will actually handle the success twice which is bad. This also means that if you DON'T handle errors your success callback will be called twice but only once with the actual success.

The other reason is that in cases like what you are doing there is no way to set a good token on the service.

```
L.esri.Services.service({
  url: 'http://logistics.arcgis.com/arcgis/rest/services/World/ServiceAreas/GPServer/GenerateServiceAreas',
  token: 'badtoken'
}).metadata(function(error, response){
  // so how do you retry with correct auth?
  console.log(error);
});
```

**Comment by patrickarlt** [comment]
@jgravois we could handle things like this.

```js
L.esri.Services.service({
  url: 'http://logistics.arcgis.com/arcgis/rest/services/World/ServiceAreas/GPServer/GenerateServiceAreas',
  token: 'badtoken'
}).metadata(function(error, response){
  if (error && error.authenticate) {
    // handle an auth error. The error response will have an authenticate method
    error.authenticate('goodtoken');
    return;
  }
  
  if (error) {
    // handle a non-auth error
    return;
  }
  
  // handle success
});
```

**Comment by jgravois** [comment]
yeah, i guess im just confused by the fact that for other problems we encounter we fire `requesterror` **and** run `callback.call()`, but when we encounter a problem with a hardcoded token, we fire `authenticationrequired` and abort, expecting the developer to be listening for it.

im guessing that just because my own scenario doesn't result in a callback being called twice, there are others that would if we made any changes to the logic.

**Comment by patrickarlt** [comment]
>  guessing that just because my own scenario doesn't result in a callback being called twice, there are others that would if we made any changes to the logic.

Ok assume that your callback is called with an error code 498 token required. What do you do? You  obviously want to try to request again but how do you do that? How do you try to request again without calling the users callback twice or making the user repeat the request again? Remember that in most cases like `L.esri.FeatureLayer` the user doesn't know anything about the requests since they are all handled internally.

**Comment by patrickarlt** [comment]
@jgravois I'm going to consider to approach i outlined above for 1.0. Right now it might make a big breaking change in some apps so I want to keep it out for now.

**Comment by ngoldman** [comment]
@patrickarlt I try to handle errors in callbacks like so:

```js
function (err, response) {
  if (err) return errorHandler(err)
  // anything past this point assumes success with a healthy response object
}
```

This to me is cleaner as it

1. handles the error immediately
1. halts the callback chain by returning
1. keeps error handling logic out of individual callbacks
1. encourages maintainers to come up with & stick to a consistent & systematic way of dealing with errors in the lib
1. keeps code clean by removing an unnecessary `else` block

See http://blog.timoxley.com/post/47041269194/avoid-else-return-early for an opinion piece that makes my position sound smarter

**Comment by ngoldman** [comment]
Okay after a closer read I agree with @patrickarlt's approach above (https://github.com/Esri/esri-leaflet/issues/575#issuecomment-119275861).
