### ISSUE TITLE
Switch to passing URL in options for layers?

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet#578]
In RC 4 I refactored all `Task` and `Service` objects to accept `url` in the options like so:

```js
L.esri.Tasks.query({
  url: 'https://...'
});
```

I've been debating making the change for all the layers for a few reasons.

1. Everything now accepts `options` as its first argument, except maybe `BasemapLayer`
2. We can warn about not passing `url` more efficiently which we currently don't do
3. Opens the door for things like https://github.com/Esri/esri-leaflet/issues/570 later
4. Makes passing params to the underlying services on layers easier

The major problem is that if this goes into 1.0 we have 2 different patterns for layer initialization across the 2 branches 1.0.0 vs 0.9.0. I might be able to make this backward compatible by checking if the first parameter is an object though.

@jgravois @ngoldman

**Comment by jgravois** [comment]
my gut reaction is that we're better off tackling the refactor now (rather than later) and that we can probably get away with skipping effort on backwards compatibility until such a time that we come across a bug that we can't conveniently port back to 0.9.x.

that being said, i don't have any plans personally to tackle #570 and i haven't encountered any problems with the current architecture so i'm pretty ambivalent about the whole thing.

if you want to go ahead with it, i think it'd be worthwhile to package a snapshot of the documentation site that corresponds with 0.9.x and either host it ourselves or at a bare minimum make it available for download without requiring a build.

**Comment by ngoldman** [comment]
I would recommend normalizing towards an options object across public functions for the sake of both releases (for Leaflet 0.7.3 and 1.0.0), as it's a better pattern and a stable release with a major version change is the time to do that. This would follow with my recommendation re: #577.

@patrickarlt @jgravois
