### ISSUE TITLE
Support for Esri vector tiles

### ISSUE THREAD

**Issue by alaframboise** [Esri/esri-leaflet#631]
It would be great to see support for these guys.  e.g.

http://basemapsbeta.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer/tile/2/0/0.pbf

**Comment by patrickarlt** [comment]
I am for sure doing this. But I'm taking a wait and see approach for now since I would rather implement it on top of MapBox GL JS directly assuming our tiles will be compatible with it rather then bundling it with our customized closed source renderer.

**Comment by brightrain** [comment]
:+1: Agree and would love to take this for a spin as soon as it's ready. Any word on compatibility?

**Comment by jgravois** [comment]
SpatialServer/Leaflet.MapboxVectorTile#45

**Comment by StephanGeorg** [comment]
Yes, support for the vector tiles in the Esri leaflet plugin would be great. Does anybody tried with [Hoverboard](https://github.com/devTristan/hoverboard)?

**Comment by bendalton** [comment]
+1 I fully support this!

**Comment by patrickarlt** [comment]
@bendalton @brightrain  an initial proof-of-concept if available at https://github.com/Esri/esri-leaflet-vector-basemap-poc.

I hope to have a full library available by early April. But the proof of concept could help you bring it to your apps earlier if you want.

**Comment by brightrain** [comment]
:trophy:

**Comment by jgravois** [comment]
took awhile to get to it, but i refactored pat's work as a plugin in the same repo.  its now called [`esri-leaflet-vector`](https://github.com/esri/esri-leaflet-vector)

```js
L.esri.Vector.basemap('Newspaper').addTo(map);
```
live sample:
http://esri.github.io/esri-leaflet/examples/vector-basemap.html

**Comment by agaffiga** [comment]
Is Imagery not available as a vector basemap yet?

**Comment by jgravois** [comment]
aerial photography is just a raster layer that's been baked into the vector tiles in ArcGIS Online like [Hybrid](https://www.arcgis.com/home/item.html?id=8fad42206b6d4efcbd02623dba4554e4). 

In Esri Leaflet you'd load the two layers seperately.

```js
L.esri.basemapLayer('Imagery').addTo(map);
L.esri.Vector.basemap('Hybrid').addTo(map);
```
http://jsbin.com/hakuwul/edit?html,output

due to the lack of sync, flickering on pan/zoom, [caveats](https://github.com/mapbox/mapbox-gl-leaflet/tree/leaflet-master#motivation) and general nature of the underlying dependencies, it'd probably be worth adding a note to both the sample and repo that its ***experimental***.

**Comment by agaffiga** [comment]
Gotcha, thanks!

Ann Gaffigan
Owner/CEO
Gazelle Incorporated
714-793-9739
