### ISSUE TITLE
Building on windows

### ISSUE THREAD

**Issue by rowanwins** [Esri/esri-leaflet#659]
Gday guys,

Not sure if its just me but I've had some troubles getting the esri-leaflet to build on my windows machine. 

The build kept failing saying
`````
'.' is not recognized as an internal or external command, operable program or batch file
`````

In the end I worked it out by replacing the following in the package.json
````
    "build": "./scripts/build.js",
````
with
````
    "build": "node ./scripts/build.js",
````
Not sure if this is the best way to tackle this or if such a fix would effect macs, I'm sure you guys are more across the issues than me :)

Cheers,
Rowan

**Comment by jgravois** [comment]
it looks like this is because the [first line](https://github.com/Esri/esri-leaflet/blob/master/scripts/build.js#L1) of the script declares an instruction to run with `node` via a UNIX path.  see [this thread](http://stackoverflow.com/questions/10396305/npm-package-bin-script-for-windows) for more info.

i did a quick check and calling 'node ./scripts/build.js' works just fine on a mac so i'm game for accepting the change in the interest of cross-compatibility.

**Comment by patrickarlt** [comment]
:+1:

**Comment by rowanwins** [comment]
Awesome, glad your happy with that approach. I currently have a pull request open for another issue and for some reason the change for the above has been included in that PR so sorry about that (think I need to start working in branches or something like that....).
