### ISSUE TITLE
Adding a FeatureLayer with an unresponsive service leads to an error when the layer is removed (1.0.0)

### ISSUE THREAD

**Issue by PatrickKing** [Esri/esri-leaflet#705]
My app is dealing with some public services that may or may not respond (or even exist) when we add layers for them. After some debugging, it looks like an issue with FeatureGrid, where `onAdd` is never called if the service is unresponsive. When the layer is removed, `onRemove` accesses an [undefined `_map`](https://github.com/Esri/esri-leaflet/blob/v1.0.0/src/Layers/FeatureLayer/FeatureGrid.js#L26) and crashes.

**Comment by jgravois** [comment]
if you're dealing with services which may or may not exist, why not send along your own [metadata](http://esri.github.io/esri-leaflet/api-reference/services/service.html) request and confirming a valid response **before** you try and add the layer to the map?

```js
var fl = L.esri.featureLayer({
  url:'http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3'
});

fl.metadata(function(err, response) {
  if (response) {
    fl.addTo(map);
  }
});
```

**Comment by patrickarlt** [comment]
@PatrickKing Are you using the esri-leaflet-renders plugin? Esri Leaflet just handles invalid service URLs with 404 codes on the queries so this might be better posted under https://github.com/Esri/esri-leaflet-renderers if you are using it. Otherwise without a reproduction case I cant do anything about this.

If you want to validate the layer before adding it the code @jgravois gave will work.

**Comment by PatrickKing** [comment]
Thanks for the pointers! Testing for a metadata response before adding the layer to the map has reliably solved this issue for me. I am using esri-leaflet-renderers, though I didn't see how it was responsible for the problem. 

One small remaining gripe, the metadata request has no distinct event handler for timeouts. I guess I will use a `window.setTimeout` callback myself.
