### ISSUE TITLE
Best way to set opacity for Feature Layers?

### ISSUE THREAD

**Issue by daniel-sabourin** [Esri/esri-leaflet#747]
Hello again,

So the application I'm creating allows users to add whatever layers they want to a leaflet map. As such, whatever different types of layers exist, I need to be able to support it. The feature I'm adding is a slider to control the opacity of all the different layers that are on the map. All the other types of layers have an easy to use `setOpacity(0.5)`, however FeatureLayers do not.

What I've been doing has been calling `setStyle( { opacity: 0.5, fillOpacity: 0.5 } )`. I ran into a problem where new features downloaded wouldn't have the style from esri-leaflet-renderers. I submitted an [issue](https://github.com/Esri/esri-leaflet-renderers/issues/106) and we worked towards a solution. The solution was good, except for as @kneemer pointed out, it only supports simple renderers. My current "solution" is to call `resetStyle()` and then `setStyle(...)` on the load event for the layer. Not ideal, but it works.

Another issue that I noticed was that this didn't set the opacity for points/markers/icons. The documentation for Feature Layer says that setStyle deals with PathOptions, setting either opacity or fillOpacity did nothing.

One idea that I had was to find the graphic/SVG DOM element for the feature layer, and set the opacity on that with CSS styling. Something essentially like this `fl.layers['1'].{_icon/_path}.parentElement.style.opacity = 0.5`. This worked great, except for the fact that if you add multiple feature layers of the same "type" to the map, they all share the same svg graphic, thus the opacity of one layer affected all the others. A way around this would be instead of calling parentElement, you just iterate through all the _icons/_paths and set opacity on that. That works, except for the performance is really bad, as expected.

Apologies for the rambling, but the tl;dr is what is the best way to set opacity for feature layers, which works on all types. Points/polygons/lines, simple/complex renderers. Could there be a `setOpacity(0.5)` like all the other esri-leaflet layers?

**Comment by jgravois** [comment]
> Could there be a `setOpacity()` like all the other esri-leaflet layers?

unfortunately, since some Leaflet point symbol types (like `L.marker`) include a constructor option and method for setting [transparency](http://leafletjs.com/reference.html#marker-setopacity), and others (like `L.icon`) do not, we'd have just as much trouble trying to implement the functionality internally as you are in your own application.

my initial reaction is that attempting to *wrap disparate layer types and ensure that consistent symbolization customizations can be applied* is beyond the scope of what this plugin should do.  that being said, it could definitely make sense in the context of another plugin (perhaps even within esri-leaflet-renderers) if someone was game for tackling it.

**Comment by patrickarlt** [comment]
> One idea that I had was to find the graphic/SVG DOM element for the feature layer, and set the opacity on that with CSS styling. Something essentially like this fl.layers['1'].{_icon/_path}.parentElement.style.opacity = 0.5. This worked great, except for the fact that if you add multiple feature layers of the same "type" to the map, they all share the same svg graphic, thus the opacity of one layer affected all the others. 

If you are using Esri Leaflet 2.0 (and Leaflet 1.0) you can actually work around this problem very easily.

Take a look at our [Ordering Layers](http://esri.github.io/esri-leaflet/examples/layer-ordering.html) example. Each call to `map.createPane('name');` returns that DOM element you are trying to find.

So for example you could do something like this:

```js
var pane = map.createPane('something');

pane.style.opacity = 0.5;

var layer = L.esri.featureLayer({
  url: '...',
  pane: 'something'
}).addTo(map);
```

This is imperfect at best since now you have a custom pane that you have to deal with the order of in the DOM but it is a way forward.

This also has me thinking we might be able to implement a `featureLayer.setOpacity(0.5)` method by giving each `FeatureLayer` its own renderer (`L.SVG` or  `L.Canvas`) and get the opacity on the resulting `<svg>` or `<canvas>` element. It might be a little work though and there might be some conflict between the `renderer` and `pane` options that would need to be investigated.

**Comment by Mak-NOAA** [comment]
@jgravois @gavinr I know this issue is old but our site has similar issue. We have tile, dynamic and feature layers and need an option for transparency when it comes to feature layers. Currently we use the setOpacity for all layers:
https://github.com/nwfsc-fram/warehouse/blob/master/server/app/view2/view2.js#L948

and as expected feature layers fail.

Has there been any progress towards this since 2016?

**Comment by gavinr** [comment]
@Mak-NOAA have you tried the workaround that [Patrick mentioned](https://github.com/Esri/esri-leaflet/issues/747#issuecomment-187803926)?

**Comment by Mak-NOAA** [comment]
@gavinr  I haven't tried that and not sure how that would work with our code as we have 1 single pane called "custom":
https://github.com/nwfsc-fram/warehouse/blob/master/server/app/view2/view2.js#L562

And we have a bunch of layers : https://www.nwfsc.noaa.gov/data/map

<img width="1261" alt="Screen Shot 2020-07-10 at 2 06 12 PM" src="https://user-images.githubusercontent.com/20570382/87204575-057cec00-c2ba-11ea-871a-8ef749f4ecea.png">

I need the ability to change the opacity for each layer so do I need multiple panes? Sorry if this is newbish type of questions :)

**Comment by patrickarlt** [comment]
@Mak-NOAA there are 2 ways you could do this:

1. Change your setup to have 1 pane per layer and set opacity on the pane as I talked about in https://github.com/Esri/esri-leaflet/issues/747#issuecomment-187803926.
2. Use a combination of `featureLayer.setStyle()` (for features loaded in the future) and `featureLayer.eachFeature()` (for currently loaded features) to update the opacity of each individual feature in the feature layer to have the proper opacity.

**Comment by Mak-NOAA** [comment]
Thanks @patrickarlt I'll experiment with those options. For now we have taken the opacity out of production.

**Comment by Mak-NOAA** [comment]
@patrickarlt @gavinr the custom pane worked for us. Here were my changes https://github.com/nwfsc-fram/warehouse/commit/35d6fa3c4af93e8eeb26e9cf5f05dba961a60145

**Comment by jwasilgeo** [comment]
Closing as this is now in "FAQ" status with ideas discussed above for posterity.
