### ISSUE TITLE
Add copyright and license to 2.x minified build

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/esri-leaflet#764]
* Browser and version: 

Chrome 49

* Version of Leaflet (`L.version`):

1.0.0-beta.2

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.0-beta.8, `master`

* I'm loading/bundling the library using:

[2.x CDN](https://cdn.jsdelivr.net/leaflet.esri/2.0.0-beta.8/esri-leaflet.js)

What happens: no mention of the copyright and license.
```
!function(t,e){"object"==typeof exports&&"undefined"!=typeof module?e(exports,require("leaflet")):...
```

I was expecting something like (copyright year is that of repository's first commit):
```
/*!
 * Esri Leaflet 2.0.0-beta.8 (https://github.com/Esri/esri-leaflet)
 * Copyright 2013 Esri
 * Licensed under Apache 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 */
!function(t,e){"object"==typeof exports&&"undefined"!=typeof module?e(exports,require("leaflet")):...
```

The [1.x CDN](https://cdn.jsdelivr.net/leaflet.esri/1.0.2/esri-leaflet.js) version has copyright and license text.

**Comment by jgravois** [comment]
thanks for pointing this out @MikeTschudi!  the [debug](https://cdn.jsdelivr.net/leaflet.esri/2.0.0-beta.8/esri-leaflet-debug.js) copy on the CDN has the appropriate copyright text, but it looks like comments are getting stripped out in the [uglified](https://github.com/Esri/esri-leaflet/blob/master/profiles/production.js) rollup build that we just switched to.

i'll make sure to get this sorted out so that our next release includes the appropriate info (as we had up until [2.0.0-beta.7](https://cdn.jsdelivr.net/leaflet.esri/2.0.0-beta.7/esri-leaflet.js)).
