### ISSUE TITLE
Get DynamicMapLayer.getLayers() does not return layers

### ISSUE THREAD

**Issue by bbehling** [Esri/esri-leaflet#781]
* Browser and version:
 Chrome 50.0.2661.102 m

* Version of Leaflet (`L.version`):
1.0.0-rc.1

* Version of esri Leaflet (`L.esri.VERSION`):
2.0.0

* I'm loading/bundling the library using:

ie: [CDN](https://cdn.jsdelivr.net/leaflet.esri/2.0.0/esri-leaflet.js

Steps to reproduce the error:
1. Add a dynamic layer to the map
2.Wait for the layer to load
3. In the load callback function, call getLayers() on the dynamic layer

What happens is getLayers() returns false.

I was expecting an array of layers on the MapService that are being shown

http://jsbin.com/datogesuja/8/edit?html,output

**Comment by jgravois** [comment]
the API reference could be a **lot** clearer on this, but the `getLayers()` method doesn't fire off a request for service metadata describing which layers are visible by default, it simply passes back information present in the [layer constructor](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/DynamicMapLayer.js#L40) options.

my reply in [issue #566](https://github.com/Esri/esri-leaflet/issues/566#issuecomment-219588006) is relevant here too because i describe the same technique you'd use to fetch the layers and their default visibility.

**Comment by jgravois** [comment]
happy to discuss this more if it'd be helpful.
