### ISSUE TITLE
Stream layer

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#794]
try and turn [this](https://gist.github.com/patrickarlt/7803ac129d8b15d79c72) into a plugin

**Comment by rowanwins** [comment]
Gday @jgravois 

I'm intrigued by this, I recently did some work on displaying a web socket data feed using cesium and it worked a treat! 

I've just had a quick look and it looks like there are a [few sample services](https://geoeventsample3.esri.com:6443/arcgis/rest/services/SeattleBus/StreamServer) available so I might take a bit of play and see how I get on.

Cheers
Rowan

**Comment by jgravois** [comment]
> I might take a bit of play and see how I get on.

please do.

**Comment by rowanwins** [comment]
Gday @jgravois 

Well here is my [first pass at a plugin](https://github.com/rowanwins/esri-leaflet-socket
). The pseudo-code was certainly a great star , I just made a few tweaks around the edges as I was unable to get a few things going.

The main issue I'm running into is that because I'm extending from the featureLayer I appear to be inheriting its map events (from the featureManager?), on map zoom or pans it is sending requests to load new features with the new bbox params. So I need to figure out how to remove the events related to this layer... I'm thinking I should be able to do something like
````
    this._map.off('zoomend', this._handleZoomChange, this);
````

Anyway any feedback welcome,
Cheers

**Comment by jgravois** [comment]
very cool!  i'll be able to take a deeper look (and hopefully provide a few suggestions) sometime soon.

**Comment by rowanwins** [comment]
I just discovered that you can actually pass some parameters to your socket connection like where clauses and bbox extents so I'll have a bit of a play at incorporating them...

**Comment by rowanwins** [comment]
Gday @jgravois 

Well I just pushed a fairly major update and I think I'm reasonably happy with how it's progressing now. You can basically define where queries, extents and fields.  Anyway when you've got a bit of time I'd love some feedback because I'm sure some improvements can be made.

Cheers

**Comment by jgravois** [comment]
i've added a link to @rowanwins' plugin to the esri-leaflet website.  nice work!
http://esri.github.io/esri-leaflet/plugins/
