### ISSUE TITLE
Querying a FeatureLayer that intersects a circle gives no results

### ISSUE THREAD

**Issue by Metalyph** [Esri/esri-leaflet#821]
* Browser and version:
Google Chrome, Version 52.0.2743.82 m (64-bit)

* Version of Leaflet (`L.version`):
1.0.0-rc.2

* Version of esri Leaflet (`L.esri.VERSION`):
2.0.1

I'm trying to use a circle geometry object to do a spatial query.

jsBin example: https://jsbin.com/lupowab/edit?js,console,output

The code is not returning any errors, but for some reason the query itself returns nothing, when there are clearly features intersecting the circle. I've tried this same method with a rectangle, and it works fine.  Are circles not able to be used for spatial queries?  Is there a possible workaround for this?

**Comment by Metalyph** [comment]
Sorry, I just realized I can use the `nearby()` function instead.

**Comment by jgravois** [comment]
the problem you encountered initially was the result of the fact that in Leaflet, `L.circle.toGeoJSON()` returns a point, not an actual geometric representation of the circle itself and thats what is passed along in your query to the service.

since points don't often intersect other points, we added the [`nearby()`](http://esri.github.io/esri-leaflet/api-reference/tasks/query.html) function for convenience.  glad you found it.
