### ISSUE TITLE
jwt integration

### ISSUE THREAD

**Issue by mepdr** [Esri/esri-leaflet#845]
The arcgis service is behind a web application using jwt token for authorizing the requests. Is there a simple way to force all requests to have such token in the header 'Authorization'? Is it visible to extend featureLayer to support such option?

**Comment by jgravois** [comment]
the foundation of the generic request code used by `L.esri.featureLayer` can be found [here](https://github.com/Esri/esri-leaflet/blob/master/src/Request.js#L117-L127).  

the code block even demonstrates how to set an [`xmlHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) header value programmatically.

```js
httpRequest.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
```

> Is it visible to extend featureLayer to support such option?

you're certainly welcome to attempt to extend this library yourself to handle this type of custom authentication, but we wouldn't incorporate a change like that in the repository because we already support the token based security strategy employed by ArcGIS Server and ArcGIS Online.

https://developers.arcgis.com/authentication/

**Comment by mepdr** [comment]
Thanks for the answer, I see your point and I agree that it shouldn't be integrated in the library.
Is there a way to intercept the request to set the header or should I change the source code?

**Comment by jgravois** [comment]
I pointed you at the relevant source code to assist you in making your own changes.  with regard to intercepting requests, we don't have anything comparable to the JSAPI's [`setRequestPreCallback()`](https://developers.arcgis.com/javascript/3/jsapi/esri.request-amd.html#esrirequest.setrequestprecallback), if thats what you're asking.
