### ISSUE TITLE
setWhere/getWhere for DynamicMapLayer

### ISSUE THREAD

**Issue by mepdr** [Esri/esri-leaflet#867]
It'd be very useful to have the setter and getter methods for the where clause, currently available in `FeatureLayer`, exposed by `DynamicMapLayer`objects. In addition they should expose the same signatures for a better and simpler manipulation of the all available layers without delving into the details if a layer is a  `FeatureLayer` or a `DynamicMapLayer` instance.

**Comment by rowanwins** [comment]
Hi @mepdr 

When using a Dynamic Map Layer you can use the `getLayerDefs` and `setLayerDefs` methods, these do essentially the same thing as the where clause. Although because a Dynamic Map Layer can contain multiple layers you are given a bit more functionality and can pass in an object such as `{5:"STATE_NAME='Kansas'", 4:"STATE_NAME='Kansas'}.` whereby you pass different queries to different layers.

Does that make sense?

Cheers

**Comment by mepdr** [comment]
Beside the different naming, the main issue is that `setLayerDefs` lacks the callback parameter.

**Comment by rowanwins** [comment]
okay @mepdr that helps to clarify the issue somewhat.

**Comment by jgravois** [comment]
i'm having a hard time envisioning what you're suggesting.  

* if we exposed `dynamicMapLayer.setWhere()` how would folks articulate which layer they wanted to apply a definition expression to?
* since **one** request is made for a map image which includes multiple layers, what would be the value of exposing multiple individual callbacks?

**Comment by mepdr** [comment]
Raising multiple callbacks (one for each layer) can be enough general to allow user to understand when each layer has been loaded.

**Comment by jgravois** [comment]
that's my point.  the layers don't load individually.  they're all drawn within a single image.

**Comment by mepdr** [comment]
Didn't understand that. At this point, firing one callback when all layers has been drawn would be better too.

**Comment by jgravois** [comment]
the event below is already fired after the image has been retrieved from the service and drawn.

```js
dynamicMapLayer.on('load', function (e) {
});
```

**Comment by jgravois** [comment]
closing based on the information already provided, but happy to chat more if anyone has further questions.
