### ISSUE TITLE
handle json output format?

### ISSUE THREAD

**Issue by derekeder** [Esri/esri-leaflet#876]
I'm attempting to work with a layer that supports JSON, but not GeoJSON, as an output format: https://utility.arcgis.com/usrsvcs/servers/96bec60971e8401885894c0066fbb881/rest/services/CSO/CSO_Final/FeatureServer/0/

Considering that [GeoJSON is the default output format for this library](https://github.com/Esri/esri-leaflet/blob/0c3633b69171460926f403504e809e0486200222/src/Tasks/Query.js#L102) but it is not listed as one of the [officially supported output formats](http://help.arcgis.com/en/arcgisserver/10.0/apis/rest/formattypes.html), would it make sense for this library to support JSON as an output format as well?
- Browser and version: Firefox 49.0.2
- Version of Leaflet (`L.version`): 1.0.0?
- Version of esri Leaflet (`L.esri.VERSION`): 2.0.4

**Comment by jgravois** [comment]
thanks for reporting this issue. 

technically we already *do* support feature services that only emit Esri's Geoservices JSON. I wasn't aware that there were any ArcGIS Online hosted feature services that still *don't* support emitting GeoJSON. unfortunately our code currently makes the same [incorrect assumption](https://github.com/Esri/esri-leaflet/blob/20d7d98903e932d3e72af907a4039063f0cc9d0a/src/Util.js#L106-L109). This means that we are failing to trigger the fallback condition of just asking for `json` and converting it to GeoJSON internally.

> GeoJSON ... is not listed as one of the officially supported output formats

you can find more up to date REST documentation for ArcGIS Server [here](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Query_Feature_Service_Layer/02r3000000r1000000/).  `f=geojson` support was added in 10.4.1. And has existed in (most) ArcGIS Online hosted feature services for quite some time.

Ultimately I'd like to pursue two separate courses of action

- [ ] i'll log a request to ask that services like your own support start emitting `geojson` natively.
- [ ] tweak our own regex in the interim to make sure we ask for plain old `json` when the service url starts with 'utility.arcgis.com'.

---
**a couple questions for you**

* how was the feature service url that you shared published?
* is it the output of running an analysis in ArcGIS Online?

**Comment by derekeder** [comment]
thanks @jgravois! that fix for using `json` for utility.arcgis.com would work for us.

Regarding your questions, I'm not the one that published them. I'll reach out to my contact at MWRD and see if they can find the answers.

**Comment by jgravois** [comment]
i just got clarification that 'utility.arcgis.com' urls actually indicate that ArcGIS Online was used to embed credentials and proxy a secure service hosted somewhere else.  

Since these services can originate from ArcGIS Server boxes of unknown vintage the course of action I suggested previously (and have proposed formally in #882) seems appropriate.

**scenario #1 - ArcGIS Server feature layer url**
1. request `f=json` initially
2. fire off a metadata request to the service
3. if the service supports `f=geojson`, switch to that, if not continue to parse clientside

**scenario #2 - utility.arcgis.com url**
same as above

**scenario #3 - all other arcgis.com feature layer urls**
1. assume support for `f=geojson` and ask for it immediately.
