### ISSUE TITLE
Calling setWhere fires the addfeature event twice.

### ISSUE THREAD

**Issue by mepdr** [Esri/esri-leaflet#886]
Calling setWhere results in firing the addfeature event twice. (seems related to https://github.com/Esri/esri-leaflet/pull/790)
Example: http://jsbin.com/kiripelipa/edit?html,output

* Browser and version:

Chrome 54

* Version of Leaflet (`L.version`):

1.0.1

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.4

**Comment by goldenlimit** [comment]
Debug this issue and turns out that the problem potentially related to: https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureLayer.js#L122-L142

That createLayers & addLayers method fire 'addfeature' event twice and I assume that's the reason the addfeature event triggered twice @jgravois
