### ISSUE TITLE
Four requests for each feature layer, why?

### ISSUE THREAD

**Issue by kt-weyert** [Esri/esri-leaflet#887]
* Browser and version:

Chrome 54

* Version of Leaflet (`L.version`):

0.7.7

* Version of esri Leaflet (`L.esri.VERSION`):

1.0.4

Steps to reproduce the error:

Custom ESRI feature layer

What happens is [X].

For each feature layer I am adding to the ESRI leaflet map it appears to issue four requests. I don't understand why this happening. Is this a Leaflet behaviour?

I was expecting [Y].

A single request for each layer

**Comment by jgravois** [comment]
from the [API Reference](http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html):

> `L.esri.FeatureLayer` divides the current map extent into a grid of individual cells and uses them to fire queries to fetch nearby features. This technique is comparable to MODE_ONDEMAND in the ArcGIS API for JavaScript.

Using a grid of predictable cells rather than the extent of the map allows us to leverage browser cache when people pan and zoom around.  This is because folks are very likely to request the same cell again and very *unlikely* to reframe the map on the same exact extent.

**Comment by weyert** [comment]
Aha, that's a fair point but for performance reasons I would prefer to have one request (as it takes upto 10secs to finish one query) would this somehow be possible? If not, how would I be able to make this change?

**Comment by jgravois** [comment]
please see #414

**Comment by weyert** [comment]
Thank you, I will have a look, jgravois!
