### ISSUE TITLE
https://esri.github.io/esri-leaflet/examples/editing.html

### ISSUE THREAD

**Issue by mikila85** [Esri/esri-leaflet#900]
* Browser and version:

Chrome latest 54.*

* Version of Leaflet (`L.version`):

Your Demo

Steps to reproduce the error:

go here:
https://esri.github.io/esri-leaflet/examples/editing.html

errors in JS and "Lets Edit!" button doesnt work :(

**Comment by jgravois** [comment]
this was actually reported the other day in #899, and quite awhile ago (in Esri/esri-leaflet-doc#15)

since i had the editing sample commented out in the table of contents of our production site, i *thought* it was safe to back burner a fix, but i guess folks are either using search engines to find the content or following inbound links, and apparently frequently.

because of this, i took the time this morning to bump/fix the sample, so its now live and promoted appropriately.  thanks for reporting!

**Comment by mikila85** [comment]
Wow awesome :)
