### ISSUE TITLE
targeting specific MapServer layer w/ tiledMapLayer

### ISSUE THREAD

**Issue by danielduhh** [Esri/esri-leaflet#939]
* Browser and version:

all

* Version of Leaflet (`L.version`):

0.7.7

* Version of esri Leaflet (`L.esri.VERSION`):

1.0.0-rc.5

tiledMapLayer returns all layers from MapServer
passing a layers property with an array for layer id's does not work. Maybe it's not offered? If not, how can I target a specific layer on a MapServer with tiledMapLayer?

**Comment by jgravois** [comment]
`tiledMapLayer` retrieves cached images with whatever layers were included in the original cartography. passing the same url to `dynamicMapLayer` will allow you to get more fine grained control over the image returned by the service because you'll be asking for something to be generated on the fly.

more info: http://esri.github.io/esri-leaflet/tutorials/introduction-to-layer-types.html

**Comment by jgravois** [comment]
do you have any other questions about this @danielduhh?
