### ISSUE TITLE
Will you support 3D or implement the SceneView?

### ISSUE THREAD

**Issue by okiwill** [Esri/esri-leaflet#953]
Or do you have any ideas about displaying 3D data? Using Three.js or something else?

**Comment by jgravois** [comment]
the recommended tool for displaying SceneViews is the `4.x` ArcGIS API for JavaScript.  we have no plans to attempt to port something similar to Leaflet.

https://developers.arcgis.com/javascript/latest/sample-code/webscene-slides/index.html

is there something specific that makes you hesitant about utilizing our flagship web development API?

**Comment by okiwill** [comment]
Thank you for your reply. Compared to leaflet, the flagship API is heavier. It takes more time (several seconds or longer) to load, the user experience is not so well.
Maybe I need to compromise.

**Comment by DevRapitow** [comment]
I agree with okiwill.

The new API does not inter-operate well and the documentation is difficult for me to understand.
These two factors remove any opportunity for me to use the 4.3 api unfortunately in the near term. In terms of rapid development/deployment/supportability and wide adoption Leaflet is as good as it gets

An excellent solution is to provide esri/views/SceneView access in leaflet-esri. SceneView looks fantastic.

**Comment by nickpeihl** [comment]
3D and SceneView require using webgl which is not available in Leaflet. Webgl libraries are generally very heavy in order to support the gl shaders necessary for mapping in 3D. Three.js and A-frame are two webgl frameworks that, even minified, are over 1MB of JavaScript. The original creator of Leaflet is now working with a large team on a webgl mapping framework similar to the ArcGIS api (mapbox-gl-js) which is over ten times as large as Leaflet. If you really want to get a tiny and fast 3D mapping framework you could try building it from scratch using something like regl.

**Comment by jgravois** [comment]
closing, but happy to chat further if anyone has more questions down the road.
