### ISSUE TITLE
 Uncaught TypeError: Cannot read property

### ISSUE THREAD

**Issue by m3g4mInD** [Esri/esri-leaflet#956]
Hello, some time ago i have use this layer maps and works fine, today i re-turn to touch some code i have this weird error.
Thanks

Uncaught TypeError: Cannot read property:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
<!DOCTYPE html>
    <!-- Load Leaflet from CDN-->
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js"></script>
  <!-- Load Esri Leaflet from CDN -->
  <script src="https://unpkg.com/esri-leaflet@2.0.8"></script>
  <style>
    body { margin:0; padding:0; }
    #map { position: absolute; top:0; bottom:0; right:0; left:0; }
  </style>
</head>
<body>
<style>
  #basemaps-wrapper {
    position: absolute;
    top: 11px;
    right: 110px;
    z-index: 400;
    background: white;
    padding: 10px;
  }
  #basemaps {
    margin-bottom: 5px;
  }
</style>
<div id="map"></div>
<div id="basemaps-wrapper" class="leaflet-bar">
   <select name="basemaps" id="basemaps" onChange="changeBasemap(basemaps)">
    <option value="Topographic">Topographic</option>
    <option value="Streets">Streets</option>
    <option value="NationalGeographic">National Geographic</option>
    <option value="Oceans">Oceans</option>
    <option value="Gray">Gray</option>
    <option value="DarkGray">Dark Gray</option>
    <option value="Imagery">Imagery</option>
	<option value="Terrain">Terrain</option>
    <option value="ShadedRelief">Shaded Relief</option>
  </select>
</div>
<script>
 var map = L.map('map').setView([-33.87, 150.77], 16);
  var layer = L.esri.basemapLayer('Topographic').addTo(map);
  var layerLabels;

  function setBasemap(basemap) {
    if (layer) {
      map.removeLayer(layer);
    }

    layer = L.esri.basemapLayer(basemap);

    map.addLayer(layer);

    if (layerLabels) {
      map.removeLayer(layerLabels);
    }

    if (basemap === 'Topographic'
     || basemap === 'Streets'
     || basemap === 'Oceans'
     || basemap === 'Gray'
     || basemap === 'DarkGray'
     || basemap === 'Imagery'
     || basemap === 'Streets'
     || basemap === 'Terrain'
     || basemap === 'ShadedRelief' 
	 
   ) {
      layerLabels = L.esri.basemapLayer(basemap + 'Labels');
      map.addLayer(layerLabels);
    }
  }

  function changeBasemap(basemaps){
    var basemap = basemaps.value;
    setBasemap(basemap);
  }
</script>
</body>
</html>
```
Line 103: <select name="basemaps" id="basemaps" onChange="changeBasemap(basemaps)">
Line 126:  layer = L.esri.basemapLayer(basemap);
Line 152:  setBasemap(basemap);

http://jsbin.com/zowasunuzi/edit?html,js,console,output

**Comment by jgravois** [comment]
when i copy/paste the code you supplied in this issue into jsbin, it runs just fine (as does [the sample](http://esri.github.io/esri-leaflet/examples/switching-basemaps.html) its based on).

when i open the [jsbin](http://jsbin.com/zowasunuzi/edit?html,js,console,output) you linked to directly, it throws a `"SyntaxError: Unexpected token {"` error, because you're failing to define the map center dynamically.

```js
// {{ map_center[0]}}, and {{ map_center[1] }} aren't defined
var map = L.map('map').setView([{{ map_center[0] }}, {{ map_center[1] }},16]);
```

i'm happy to dig in further if you can provide more information.

**Comment by m3g4mInD** [comment]
@jgravois thanks for trying help me, i gonna post the full code, maybe i have miss something in some point.

https://pastebin.com/raw/bjw2diez

**Comment by jgravois** [comment]
given the external dependencies referenced in that code, there's not much i can do to make sense of your error.

since you're asking for help (and not reporting a problem with the API) you might be better off posting on GeoNet or GIS StackExchange. that said, you'll need to be able to provide a simplified, complete repro case that demonstrates the problem in order for anyone to be able to help you.

https://github.com/Esri/esri-leaflet#issues
