### ISSUE TITLE
UNMET PEER DEPENDENCY in esrileaflet@2.1.1 with leaflet@1.1.0

### ISSUE THREAD

**Issue by mush** [Esri/esri-leaflet#995]
* Version of Leaflet (`L.version`):

1.1.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.1.1

Steps to reproduce the error:
Setup the a basic project with webpack and run `npm install`.

What happens is,
I see the following message:
```
├─┬ esri-leaflet@2.1.1 
│ ├── arcgis-to-geojson-utils@1.0.3 
│ ├── leaflet-virtual-grid@1.0.4 
│ └── tiny-binary-search@1.0.2 
└── UNMET PEER DEPENDENCY leaflet@1.1.0

```
I was expecting,
There shouldn't be UNMET PEER DEPENDENCY.

* I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[webpack](https://webpack.github.io/)

**Comment by mush** [comment]
This,
```
"peerDependencies": {
    "leaflet": ">= 1.0.0 < 2"
  }
```
should fix the issue.

**Comment by jgravois** [comment]
hi @mush. thanks for the report. at the moment this is expected behavior.

i made a conscious decision in #974 to temporarily cap the version of Leaflet we use internally at `v1.0.x` because of the false-positive CI test errors i documented in #967.

no one has reported any _real_ compatibility bugs with Leaflet `v1.1.0` or `v1.2.0` (yet anyway) so you're welcome to use the latest and greatest, but until i figure out how to fix our test suite, if you do you're just going to have to live with the warning.

**Comment by mush** [comment]
Thanks @jgravois.
