### ISSUE TITLE
Heatmap Layer Not Rendering Properly on Vector Basemap

### ISSUE THREAD

**Issue by sethlewis** [Esri/esri-leaflet#997]
* Browser and version:

Chrome 60, Firefox 54.0.1, IE11

* Version of Leaflet (`L.version`):

1.2.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.1.0

Steps to reproduce the error:

1. Add the heatmap plugin via CDN
2. Add the vector basemap plugin via CDN
3. Add a raster basemap to the map
4. Add a vector basemap to the map and comment it out
5. Add a heatmap feature layer to the map

Notice that when the raster basemap addTo method is called the heatmap layer renders with the prescribed radius, i.e. as normal. However, when the raster basemap is commented out and we add the vector basemap to the map, the heatmap layer appears as if its radius property has been reduced.

Working jsbin: http://jsbin.com/papunaj/1/edit?html,output

* Optional: I'm using the CDN for all script calls

**Comment by jgravois** [comment]
thanks for reporting. it'll probably be a week or two before i have time to sit down and look at this.

**Comment by jgravois** [comment]
this behavior is reproducible even if you comment out _both_ basemaps (or switch to our `"Topographic"` basemap).

it is caused by the fact that _way_ down under the hood the heatmap plugin introspects the maximum zoom level from the map when it creates a co-efficient value to weight each individual pixel. 

```js
// https://github.com/Leaflet/Leaflet.heat/blob/5885ec0ec2442876b67725c64dc537cb12c52c73/src/HeatLayer.js#L141
redraw: function()
  // ...
  v = 1 / Math.pow(2, Math.max(0, Math.min(maxZoom - this._map.getZoom(), 12)));
```
since the `"Gray"` basemap is only cached to zoom level 16, this results in a larger coefficient.

if you want the heatmap to look the same when you're using a different basemap, just pass through the same `maxZoom` in the heatmap layer constructor.

```js
L.esri.Heat.featureLayer({
    url: 'https://services.arcgis.com/rOo16HdIMeOBI4Mb/ArcGIS/rest/services/Graffiti_Reports/FeatureServer/0',
    radius: 12,
    // https://github.com/Leaflet/Leaflet.heat
    maxZoom: 16
}).addTo(map);```
```
http://jsbin.com/wohodu/edit?html,output
